[package]
name = "ecalli-layout-backend"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "app"
path = "bin/app.rs"

[dependencies]
azure_core = "0.29"
azure_storage = "0.21"
azure_storage_blobs = "0.21"
azure_identity = "0.29"
futures = "0.3"
actix-cors = "0.7"
actix-http = "3.11"
actix-rt = "2.11"
actix-web = "4.11"
dotenv = "0.15"
env_logger = "0.11"
tracing = "0.1"
gcd = "2.3"
serde = { version = "1", features = ["derive"] }
serde-aux = "4.7"
serde_json = "1"
secrecy = "0.10"
thiserror = "2"
tokio = { version = "1.47", features = ["full"] }
typespec = "0.9"

# Image processing
image = "0.25"
zip = "6"
